import = [
    "~/.config/alacritty/theme.toml",
]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "Hack Nerd Font Mono"

[window]
padding = { x = 15, y = 15 }
dynamic_padding = false
opacity = 1

[window.dimensions]
columns = 128
lines = 32

[selection]
save_to_clipboard = true
