import = [
    "~/.config/alacritty/macos.toml",
    "~/.config/alacritty/tokyo-night.toml",
]

[font]
size = 16

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 1

[window.dimensions]
columns = 128
lines = 32

[selection]
save_to_clipboard = true
